<?php

declare(strict_types=1);

/*
 * Regenerates src/Hreflang/IsoCodes.php from its reference sources:
 *
 *     php tools/generate-iso-codes.php [--iso-codes-ref=v4.20.1|latest] [--check] [output-file]
 *
 * - iso-codes (ISO 639-1 and ISO 3166-1) is read at a pinned tag, so regenerating reproduces the committed file. Pass a
 *   newer tag from https://salsa.debian.org/iso-codes-team/iso-codes/-/tags, or "latest", to pick up changes.
 * - The IANA Language Subtag Registry (ISO 639-1 and ISO 15924) has no tags: it is fetched as it currently is, and its
 *   File-Date ends up in the generated file.
 *
 * With --check, nothing is written: the codes the sources currently yield are compared with the ones in the file, and a
 * Markdown report is printed. The exit code is 0 when they match, 3 when the file is outdated and 1 on any error.
 */

const IANA_REGISTRY_URL = 'https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry';
const ISO_CODES_URL = 'https://salsa.debian.org/iso-codes-team/iso-codes/-/raw/%s/data/%s';
const ISO_CODES_TAGS_URL = 'https://salsa.debian.org/api/v4/projects/iso-codes-team%2Fiso-codes/repository/tags'
    .'?order_by=updated&sort=desc&per_page=100';
const DEFAULT_ISO_CODES_REF = 'v4.20.1';
const EXIT_OUTDATED = 3;

$isoCodesRef = DEFAULT_ISO_CODES_REF;
$output = __DIR__.'/../src/Hreflang/IsoCodes.php';
$check = false;

foreach (array_slice($argv, 1) as $argument) {
    if ($argument === '--check') {
        $check = true;

        continue;
    }

    if (str_starts_with($argument, '--iso-codes-ref=')) {
        $isoCodesRef = substr($argument, strlen('--iso-codes-ref='));

        continue;
    }

    $output = $argument;
}

if ($isoCodesRef === 'latest') {
    $isoCodesRef = latestIsoCodesTag();
}

$registry = parseIanaRegistry(fetch(IANA_REGISTRY_URL));
$iso3166 = readIsoCodes($isoCodesRef, 'iso_3166-1.json', '3166-1');
$iso639 = readIsoCodes($isoCodesRef, 'iso_639-2.json', '639-2');

$languages = sortedUnique([...$iso639, ...$registry['languages']]);
$regions = sortedUnique($iso3166);
$scripts = sortedUnique($registry['scripts']);

if ($languages === [] || $regions === [] || $scripts === []) {
    fwrite(STDERR, "A source came back empty; its format may have changed. Nothing was written.\n");
    exit(1);
}

if ($check) {
    exit(
    checkAgainst(
        $output,
        ['LANGUAGES' => $languages, 'REGIONS' => $regions, 'SCRIPTS' => $scripts],
        $isoCodesRef,
        $registry['fileDate'],
    )
    );
}

$php = <<<PHP
    <?php

    declare(strict_types=1);

    namespace Lbonnet\TechnicalSeoBundle\Hreflang;

    /**
     * Generated by tools/generate-iso-codes.php from iso-codes $isoCodesRef and the IANA Language Subtag Registry
     * (File-Date {$registry['fileDate']}); regenerate rather than edit. Keys are the codes; values are only there for
     * O(1) lookups.
     *
     * - LANGUAGES: ISO 639-1, as listed by either source, so a code only one of them still carries is never reported.
     * - REGIONS: ISO 3166-1 alpha-2, officially assigned codes only. The IANA registry also carries exceptionally
     *   reserved codes (EU, UN, ...), which Google ignores in hreflang.
     * - SCRIPTS: ISO 15924, from the IANA registry (the more current of the two), private-use codes excluded.
     */
    final class IsoCodes
    {

    PHP;

$php .= renderConstant('Lower-case ISO 639-1 language codes.', 'LANGUAGES', $languages)."\n"
    .renderConstant('Upper-case ISO 3166-1 alpha-2 region codes.', 'REGIONS', $regions)."\n"
    .renderConstant('Title-case ISO 15924 script codes.', 'SCRIPTS', $scripts)
    ."}\n";

if (file_put_contents($output, $php) === false) {
    fwrite(STDERR, "Could not write $output.\n");
    exit(1);
}

printf(
    "Wrote %s: %d languages, %d regions, %d scripts (iso-codes %s, IANA File-Date %s).\n",
    $output,
    count($languages),
    count($regions),
    count($scripts),
    $isoCodesRef,
    $registry['fileDate'],
);

/**
 * Compares the codes the sources yield with the ones in the generated file, and prints a Markdown report.
 *
 * @param array<string, list<string>> $tables constant name => codes the sources currently yield
 */
function checkAgainst(string $file, array $tables, string $isoCodesRef, string $fileDate): int
{
    require $file;

    $changes = [];

    foreach ($tables as $name => $codes) {
        $current = array_keys(constant('Lbonnet\\TechnicalSeoBundle\\Hreflang\\IsoCodes::'.$name));
        $added = array_values(array_diff($codes, $current));
        $removed = array_values(array_diff($current, $codes));

        if ($added !== [] || $removed !== []) {
            $changes[$name] = [$added, $removed];
        }
    }

    if ($changes === []) {
        printf("The ISO codes are up to date (iso-codes %s, IANA File-Date %s).\n", $isoCodesRef, $fileDate);

        return 0;
    }

    printf(
        "The ISO codes used to validate hreflang values are outdated (iso-codes %s, IANA File-Date %s):\n\n",
        $isoCodesRef,
        $fileDate,
    );

    foreach ($changes as $name => [$added, $removed]) {
        $parts = [];

        if ($added !== []) {
            $parts[] = 'added '.formatCodes($added);
        }

        if ($removed !== []) {
            $parts[] = 'removed '.formatCodes($removed);
        }

        printf("- `%s`: %s\n", $name, implode('; ', $parts));
    }

    echo "\n";

    if ($isoCodesRef !== DEFAULT_ISO_CODES_REF) {
        printf("Set `DEFAULT_ISO_CODES_REF` to `%s` in `tools/generate-iso-codes.php`, then run", $isoCodesRef);
    } else {
        echo 'Run';
    }

    echo " `php tools/generate-iso-codes.php` and commit the result.\n";

    return EXIT_OUTDATED;
}

/**
 * @param list<string> $codes
 */
function formatCodes(array $codes): string
{
    return implode(', ', array_map(static fn(string $code): string => "`$code`", $codes));
}

/**
 * @throws JsonException
 */
function latestIsoCodesTag(): string
{
    $tags = json_decode(fetch(ISO_CODES_TAGS_URL), true, 512, JSON_THROW_ON_ERROR);
    $releases = array_values(
        array_filter(
            array_column(is_array($tags) ? $tags : [], 'name'),
            static fn(mixed $name): bool => is_string($name) && preg_match('/^v\d+\.\d+(\.\d+)?$/', $name) === 1,
        )
    );

    if ($releases === []) {
        fwrite(STDERR, "No release tag found for iso-codes.\n");
        exit(1);
    }

    usort($releases, static fn(string $a, string $b): int => version_compare(substr($a, 1), substr($b, 1)));

    return $releases[count($releases) - 1];
}

function fetch(string $url): string
{
    $context = stream_context_create([
        'http' => ['timeout' => 30, 'user_agent' => 'technical-seo-bundle/generate-iso-codes'],
    ]);
    $content = @file_get_contents($url, false, $context);

    if ($content === false || $content === '') {
        fwrite(STDERR, "Could not fetch $url.\n");
        exit(1);
    }

    return $content;
}

/**
 * @return list<string>
 * @throws JsonException
 */
function readIsoCodes(string $ref, string $file, string $key): array
{
    $data = json_decode(fetch(sprintf(ISO_CODES_URL, rawurlencode($ref), $file)), true, 512, JSON_THROW_ON_ERROR);

    return array_values(array_column($data[$key] ?? [], 'alpha_2'));
}

/**
 * Keeps the current, non-private two-letter languages and four-letter scripts of the registry.
 *
 * @return array{fileDate: string, languages: list<string>, scripts: list<string>}
 */
function parseIanaRegistry(string $registry): array
{
    $records = explode("\n%%\n", str_replace("\r\n", "\n", $registry));
    $header = array_shift($records);

    if (preg_match('/^File-Date: (\S+)/m', (string)$header, $matches) !== 1) {
        fwrite(STDERR, "The IANA registry has no File-Date; its format may have changed.\n");
        exit(1);
    }

    $languages = [];
    $scripts = [];

    foreach ($records as $record) {
        $fields = [];
        $key = null;

        foreach (explode("\n", $record) as $line) {
            if ($key !== null && str_starts_with($line, '  ')) {
                $fields[$key][count($fields[$key]) - 1] .= ' '.trim($line);

                continue;
            }

            if (str_contains($line, ': ')) {
                [$key, $value] = explode(': ', $line, 2);
                $fields[$key][] = $value;
            }
        }

        $type = $fields['Type'][0] ?? '';
        $subtag = $fields['Subtag'][0] ?? '';

        if (
            $subtag === ''
            || str_contains($subtag, '..')
            || isset($fields['Deprecated'])
            || in_array('Private use', $fields['Description'] ?? [], true)
        ) {
            continue;
        }

        if ($type === 'language' && preg_match('/^[a-z]{2}$/', $subtag) === 1) {
            $languages[] = $subtag;
        } elseif ($type === 'script' && preg_match('/^[A-Z][a-z]{3}$/', $subtag) === 1) {
            $scripts[] = $subtag;
        }
    }

    return ['fileDate' => $matches[1], 'languages' => $languages, 'scripts' => $scripts];
}

/**
 * @param list<string> $codes
 *
 * @return list<string>
 */
function sortedUnique(array $codes): array
{
    $codes = array_values(array_unique($codes));
    sort($codes, SORT_STRING);

    return $codes;
}

/**
 * Renders a lookup table, packing as many entries per line as fit in 120 characters.
 *
 * @param list<string> $codes
 */
function renderConstant(string $doc, string $name, array $codes): string
{
    $lines = [];
    $line = '       ';

    foreach ($codes as $code) {
        $entry = " '$code' => true,";

        if (strlen($line) + strlen($entry) > 120) {
            $lines[] = $line;
            $line = '       ';
        }

        $line .= $entry;
    }

    $lines[] = $line;

    return "    /** $doc */\n    public const $name = [\n".implode("\n", $lines)."\n    ];\n";
}
