<?php

declare(strict_types=1);

/*
 * Regenerates src/Hreflang/IsoCodes.php from its reference sources:
 *
 *     php tools/generate-iso-codes.php [--iso-codes-ref=v4.16.0] [output-file]
 *
 * - iso-codes (ISO 639-1 and ISO 3166-1) is read at a pinned tag, so regenerating reproduces the committed file. Pass a
 *   newer tag from https://salsa.debian.org/iso-codes-team/iso-codes/-/tags to pick up changes.
 * - The IANA Language Subtag Registry (ISO 639-1 and ISO 15924) has no tags: it is fetched as it currently is, and its
 *   File-Date ends up in the generated file.
 */

const IANA_REGISTRY_URL = 'https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry';
const ISO_CODES_URL = 'https://salsa.debian.org/iso-codes-team/iso-codes/-/raw/%s/data/%s';
const DEFAULT_ISO_CODES_REF = 'v4.16.0';

$isoCodesRef = DEFAULT_ISO_CODES_REF;
$output = __DIR__.'/../src/Hreflang/IsoCodes.php';

foreach (array_slice($argv, 1) as $argument) {
    if (str_starts_with($argument, '--iso-codes-ref=')) {
        $isoCodesRef = substr($argument, strlen('--iso-codes-ref='));

        continue;
    }

    $output = $argument;
}

$registry = parseIanaRegistry(fetch(IANA_REGISTRY_URL));
$iso3166 = readIsoCodes($isoCodesRef, 'iso_3166-1.json', '3166-1');
$iso639 = readIsoCodes($isoCodesRef, 'iso_639-2.json', '639-2');

$languages = sortedUnique([...$iso639, ...$registry['languages']]);
$regions = sortedUnique($iso3166);
$scripts = sortedUnique($registry['scripts']);

if ($languages === [] || $regions === [] || $scripts === []) {
    fwrite(STDERR, "A source came back empty; its format may have changed. Nothing was written.\n");
    exit(1);
}

$php = <<<PHP
    <?php

    declare(strict_types=1);

    namespace Lbonnet\TechnicalSeoBundle\Hreflang;

    /**
     * Generated by tools/generate-iso-codes.php from iso-codes $isoCodesRef and the IANA Language Subtag Registry
     * (File-Date {$registry['fileDate']}); regenerate rather than edit. Keys are the codes; values are only there for
     * O(1) lookups.
     *
     * - LANGUAGES: ISO 639-1, as listed by either source, so a code only one of them still carries is never reported.
     * - REGIONS: ISO 3166-1 alpha-2, officially assigned codes only. The IANA registry also carries exceptionally
     *   reserved codes (EU, UN, ...), which Google ignores in hreflang.
     * - SCRIPTS: ISO 15924, from the IANA registry (the more current of the two), private-use codes excluded.
     */
    final class IsoCodes
    {

    PHP;

$php .= renderConstant('Lower-case ISO 639-1 language codes.', 'LANGUAGES', $languages)."\n"
    .renderConstant('Upper-case ISO 3166-1 alpha-2 region codes.', 'REGIONS', $regions)."\n"
    .renderConstant('Title-case ISO 15924 script codes.', 'SCRIPTS', $scripts)
    ."}\n";

if (file_put_contents($output, $php) === false) {
    fwrite(STDERR, "Could not write $output.\n");
    exit(1);
}

printf(
    "Wrote %s: %d languages, %d regions, %d scripts (iso-codes %s, IANA File-Date %s).\n",
    $output,
    count($languages),
    count($regions),
    count($scripts),
    $isoCodesRef,
    $registry['fileDate'],
);

function fetch(string $url): string
{
    $context = stream_context_create([
        'http' => ['timeout' => 30, 'user_agent' => 'technical-seo-bundle/generate-iso-codes'],
    ]);
    $content = @file_get_contents($url, false, $context);

    if ($content === false || $content === '') {
        fwrite(STDERR, "Could not fetch $url.\n");
        exit(1);
    }

    return $content;
}

/**
 * @return list<string>
 * @throws JsonException
 */
function readIsoCodes(string $ref, string $file, string $key): array
{
    $data = json_decode(fetch(sprintf(ISO_CODES_URL, rawurlencode($ref), $file)), true, 512, JSON_THROW_ON_ERROR);

    return array_values(array_column($data[$key] ?? [], 'alpha_2'));
}

/**
 * Keeps the current, non-private two-letter languages and four-letter scripts of the registry.
 *
 * @return array{fileDate: string, languages: list<string>, scripts: list<string>}
 */
function parseIanaRegistry(string $registry): array
{
    $records = explode("\n%%\n", str_replace("\r\n", "\n", $registry));
    $header = array_shift($records);

    if (preg_match('/^File-Date: (\S+)/m', (string)$header, $matches) !== 1) {
        fwrite(STDERR, "The IANA registry has no File-Date; its format may have changed.\n");
        exit(1);
    }

    $languages = [];
    $scripts = [];

    foreach ($records as $record) {
        $fields = [];
        $key = null;

        foreach (explode("\n", $record) as $line) {
            if ($key !== null && str_starts_with($line, '  ')) {
                $fields[$key][count($fields[$key]) - 1] .= ' '.trim($line);

                continue;
            }

            if (str_contains($line, ': ')) {
                [$key, $value] = explode(': ', $line, 2);
                $fields[$key][] = $value;
            }
        }

        $type = $fields['Type'][0] ?? '';
        $subtag = $fields['Subtag'][0] ?? '';

        if (
            $subtag === ''
            || str_contains($subtag, '..')
            || isset($fields['Deprecated'])
            || in_array('Private use', $fields['Description'] ?? [], true)
        ) {
            continue;
        }

        if ($type === 'language' && preg_match('/^[a-z]{2}$/', $subtag) === 1) {
            $languages[] = $subtag;
        } elseif ($type === 'script' && preg_match('/^[A-Z][a-z]{3}$/', $subtag) === 1) {
            $scripts[] = $subtag;
        }
    }

    return ['fileDate' => $matches[1], 'languages' => $languages, 'scripts' => $scripts];
}

/**
 * @param list<string> $codes
 *
 * @return list<string>
 */
function sortedUnique(array $codes): array
{
    $codes = array_values(array_unique($codes));
    sort($codes, SORT_STRING);

    return $codes;
}

/**
 * Renders a lookup table, packing as many entries per line as fit in 120 characters.
 *
 * @param list<string> $codes
 */
function renderConstant(string $doc, string $name, array $codes): string
{
    $lines = [];
    $line = '       ';

    foreach ($codes as $code) {
        $entry = " '$code' => true,";

        if (strlen($line) + strlen($entry) > 120) {
            $lines[] = $line;
            $line = '       ';
        }

        $line .= $entry;
    }

    $lines[] = $line;

    return "    /** $doc */\n    public const $name = [\n".implode("\n", $lines)."\n    ];\n";
}
